# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a64324b05f8a99cb7f39ceb1ab2d8dfd2131aeb8bf4f8692e48d156daaa013ad6856d584db500b599dcdaa968ccb334db6af5250123e161c4937e1d1ecb7cea9

test:
  secret_key_base: 3c9f86a7377bf4dae04549e418e919c1af117df022a27d9c860b79e6621cbbe1e63dc53f369efe06cd8a1dc3af4e2e4c1bf3909023bfaa0a4ec1877044986872

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
